name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install
        run: yarn

      - name: Release for Windows
        if: matrix.os == 'windows-latest'
        run: yarn make

      - name: Release for MacOS
        if: matrix.os == 'macos-latest'
        run: yarn make

      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn make

      - name: Release for Windows ARM
        if: matrix.os == 'windows-latest'
        run: yarn make -a arm64

      - name: Release for MacOS ARM
        if: matrix.os == 'macos-latest'
        run: yarn make -a arm64

      - name: Release for Linux ARM
        if: matrix.os == 'ubuntu-latest'
        run: yarn make -a arm64