name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fase: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'

      - name: Install
        run: yarn

      - name: Release for windows
        if: matrix.os == 'windows-latest'
        run: yarn make